include:
  - board: xiao_ble
    shield: banana_left
    snippet: zmk-usb-logging
  - board: xiao_ble
    shield: banana_right
    snippet: zmk-usb-logging
  - board: xiao_ble
    shield: tester_xiao 
  - board: xiao_ble
    shield: settings_reset


