manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: austlai
      url-base: https://github.com/austlai
  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
      revision: v0.3
    - name: zmk-dongle-display
      remote: austlai
      revision: e014344
  self:
    path: config
